### ISSUE TITLE
How to add pdfFontData

### ISSUE THREAD

**Issue by chris-sx** [horstoeko/zugferdvisualizer#1]
Hi, 
I want to use tt fonts in a template.

I found:
$visualizer = new ZugferdVisualizer($document);
$visualizer->setDefaultTemplate();
$visualizer->setTemplate($template);
$visualizer->addPdfFontDirectory('/fonts/ttfonts');
$visualizer->setPdfFontDefault("DejaVuSans");

But how do I have to define "pdfFontData", which is used in function instanciatePdfEngine

Thanks

**Comment by horstoeko** [comment]
Hi @chris-sx,

thank you for contributing this question. Since this library is largely based on mPDF, please search there first to see if you can find what you are looking for. In my opinion, a good starting point would be this [address](https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html). Otherwise, I can have another look myself to see if I can implement a good example...

Best regards

**Comment by chris-sx** [comment]
Hi

thanks, but how do I mix the array like in mpdf with the parameter “$document”, mPdf does not have an additional parameter 

$visualizer = new ZugferdVisualizer($document);

Viele Grüße

Christian

**Comment by horstoeko** [comment]
Hi @chris-sx,

I have published a new release [1.0.8](https://github.com/horstoeko/zugferdvisualizer/releases/tag/v1.0.8) that allows you to work with your own (user-defined) fonts. I have also adapted the [documentation](https://github.com/horstoeko/zugferdvisualizer?tab=readme-ov-file#working-with-custom-fonts) and the [examples](https://github.com/horstoeko/zugferdvisualizer/tree/v1.0.8/examples). 

I would be delighted if you could send me feedback and a "thank you" if you like.

Kind regards
